version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - data-structure-db:/var/opt/mssql
  
  algdatagateway:
    image: ${DOCKER_REGISTRY-}algdatagateway
    build:
      context: .
      dockerfile: src/AlgDataGatewayAPI/AlgDataGateway/Dockerfile

  algorithmapi:
    image: ${DOCKER_REGISTRY-}algorithmapi
    build:
      context: .
      dockerfile: src/AlgorithmAPI/Dockerfile
    ports:
      - 1555:443
      - 1556:80

  rabbitmq: 
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"  
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672" 

  datastructureapi:
    image: ${DOCKER_REGISTRY-}datastructureapi
    build:
      context: .
      dockerfile: src/DataStructureAPI/Dockerfile
    depends_on:
      - db
  calculationapi:
    image: ${DOCKER_REGISTRY-}calculationapi
    build:
      context: .
      dockerfile: src/CalculationAPI/Dockerfile

volumes:
  data-structure-db: 

